import YaMapLoader from "@/components/_location/ya-map-loader/ya-map-loader";
import Footer from "@/layout/footer/footer";
import Header from "@/layout/header/header";
import Jivo from "@/layout/jivo/jivo";
import Main from "@/layout/main/main";
import Metrika from "@/layout/metrika/metrika";
import type {Metadata} from "next";
import "../variables.css";
import "../globals.css";
import "./globals.css";
import {Inter} from "next/font/google";
import React, {Suspense} from "react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: {
      url: `/img/favicon/icon.svg`,
      type: "image/svg+xml",
    },
    apple: {
      url: `img/favicon/apple-touch-icon.png`,
      type: "image/png",
    },
  },
};

const InterFont = Inter({
  weight: ["600", "500", "400", "300"],
  style: ["italic", "normal"],
  subsets: ["cyrillic", "latin"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
    <body style={InterFont.style}>
    <YaMapLoader />
    <Header />
    <Main>
      {children}
    </Main>
    <Footer />
    {
      process.env.NODE_ENV === "production" && <>
        <Suspense>
          <Metrika />
        </Suspense>
        <Jivo />
      </>
    }
    </body>
    </html>
  );
}
