import type { Metadata } from "next";
import "./globals.css";
import {Inter} from "next/font/google";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const InterFont = Inter({
  weight: ["500", "400", "300"],
  style: ["italic", "normal"],
  subsets: ["cyrillic", "latin"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <body style={InterFont.style}>
        {children}
      </body>
    </html>
  );
}
