import type {Metadata} from "next";
import "../variables.css";
import "../globals.css";
import {Inter} from "next/font/google";
import Header from "@/layout/header/header";
import Footer from "@/layout/footer/footer";
import Main from "@/layout/main/main";
import React from "react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const InterFont = Inter({
  weight: ["600", "500", "400", "300"],
  style: ["italic", "normal"],
  subsets: ["cyrillic", "latin"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
    <body style={InterFont.style}>
    <Header />
    <Main>
      {children}
    </Main>
    <Footer />
    </body>
    </html>
  );
}
