import DynamicHeader from "@/app/(main)/_components/dynamic-header/dynamic-header";
import Footer from "@/layout/footer/footer";
import Main from "@/layout/main/main";
import Metrika from "@/layout/metrika/metrika";
import type {Metadata} from "next";
import "../variables.css";
import "../globals.css";
import "./globals.css";
import {Inter} from "next/font/google";
import Head from "next/head";
import React, {Suspense} from "react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const InterFont = Inter({
  weight: ["600", "500", "400", "300"],
  style: ["italic", "normal"],
  subsets: ["cyrillic", "latin"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
    <Head>
      <link rel="icon" href="/favicon/icon.svg" type="image/svg+xml" />
      <link rel="apple-touch-icon" href="/favicon/apple-touch-icon.png" />
    </Head>
    <body style={InterFont.style}>
    <DynamicHeader />
    <Main>
      {children}
    </Main>
    <Footer />
    <Suspense>
      <Metrika />
    </Suspense>
    </body>
    </html>
  );
}
